# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "sjh04"
repo_name: "ad-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 15

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/ad-arxiv-daily.json'
json_gitpage_path: './docs/ad-arxiv-daily-web.json'
# json_wechat_path: './docs/ad-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
# md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Planning & Control":
        filters: ["Motion Planning", "Path Planning", "Trajectory Planning",
                 "Vehicle Control"]
    "End-to-end Driving":
        filters: ["End-to-end Autonomous Driving"]
    "Prediction":
        filters: ["Trajectory Prediction", "Behavior Prediction",
                 "Interactive Prediction"]
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Self-driving", "Autonomous Vehicle"]
    "Simulation":
        filters: ["Driving Simulation", "Scenario Generation"]
    "Perception":
        filters: ["3D Detection", "Multi-Object Tracking", "BEV Perception",
                 "Camera-LiDAR Fusion"]
